on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  base-x:
    runs-on: ${{ vars.MACHINE }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache restore node_modules
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: ${{ inputs.command }}
